### ISSUE TITLE
研究Karel作业

### ISSUE THREAD

**Issue by wlnirvana** [practischool/java-materials#1]

**Comment by susutaotao** [comment]
任务描述：Assignment1的problem2：Karel机器人修复受损柱子。

小结：

一、课程的起点：编程环境的搭建——安装Eclipse、JRE or IntelliJ；安装git，获取初始代码和工程；
	1、Eclipse/JRE：Stanford定制版，屏蔽了一些复杂功能。下载失败未使用。
	2、IntelliJ和git安装：参考石墨说明文档：https://shimo.im/docs/hQwXxV9Pdyw98RKX?from=groupmessage&isappinstalled=0
	3、github获取初始工程，CS106A获取starter code：
	git clone https://github.com/practischool/java-materials.git
		错误代码：10054
		错误原因：工程太大；
		解决方法：增大缓存空间 git config --global http.postBuffer 1048576000  (1G)

二、领会基本的编程思想：
	1、自顶向下的设计思想；
	2、让计算机&人都能看懂的程序；
	3、避免最常见的一类错误：off-by-one ；

三、时间：预计各半天

**Comment by wlnirvana** [comment]
太棒啦！辛苦苏韬老师:)
