### ISSUE TITLE
研究FacePamphlet作业

### ISSUE THREAD

**Issue by wlnirvana** [practischool/java-materials#7]

**Comment by wlnirvana** [comment]
有一年用了Shahidi，多数年份用的是FacePamphlet。可以从[assignment-stats.md][1]找到更多信息。

[1]:https://github.com/practischool/java-materials/blob/master/cs106a/assignment-stats.md

**Comment by ninghe12345** [comment]
研究结果：
1、从https://github.com/gregdardis/FacePamphlet-CS106A下下载到源码
2、此工程使用awt、swing、sqlite技术栈
3、完成此作业需要掌握java gui编程及java 数据库编程、文件上传等。
4、完成此作业时，可以让学生有面向对象的思维，把类合理规划，分包、分类、分方法。
5、此作业建议给两三天的时间，高质量完成。
6、作业开始前，可以展开适当的小组讨论，提前设计好类及实现方案。

**Comment by wlnirvana** [comment]
宁老师真是太高效了！

1. awt、swing在cs106a当中应该都是被封装进了spl.jar的是吗？
2. sqlite部分（甚至文件的本地持久化）是不是在starter files里面直接提供比较好？我看2007年视频的时候，好像不记得有讲过数据库。
3. 两三天可能都不够，cs106a的每个作业好像都是提前两三个礼拜发布的。不过后面的几个都是允许结对编程的。

不过这些都是细节问题了，接下来可以思考一下如何简化作业。我们可能需要比斯坦福的starter files提供更多的初始代码给学生，一方面降低难度，另一方面争取能够实现自动化的测评。当然，与此同时如果还能保持一定的开放性让学生自由发挥，那就太棒了。
